# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a930e1d10859edc7ac8ebfbe5105ce52f02c62242a27e11c8f7c1c736afd33c1233abc2e675d26d52a6edeb5c47f5a76c037cff30b9551ae9c625ce5c63f5a

test:
  secret_key_base: 612e1ee4310b8f60cade7ddbce3fd9006fea1c91e424d5ba07ba5cfe5b4d6d3ea390697c2581101fc1ed0a6edeb1638b571849cd26776ab122fc977010696019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
